apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: ktpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe-container
        image: ndbaolam/bluemoon-fe:latest
        env:
        - name: VITE_API_URL
          value: http://be-service:8000
        ports:
        - containerPort: 80
