apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: be
  ports:
  - port: {{ .Values.be.service.port }}
    targetPort: {{ .Values.be.service.port }}
    nodePort: 30006
  type: {{ .Values.be.service.type }}
