apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ktpm
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: {{ .Values.db.image }}
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: {{ .Values.db.env.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.db.env.POSTGRES_PASSWORD }}
          - name: POSTGRES_DB
            value: {{ .Values.db.env.POSTGRES_DB }}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: ktpm
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc  
  namespace: ktpm
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-app
    meta.helm.sh/release-namespace: ktpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
