apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
