apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: ktpm
spec:
  replicas: {{ .Values.fe.replicaCount }}
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe-container
        image: {{ .Values.fe.image }}
        env:
        - name: VITE_API_URL
          value: {{ .Values.fe.env.VITE_API_URL }}
        ports:
        - containerPort: {{ .Values.fe.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: ktpm
spec:
  type: {{ .Values.fe.service.type }}
  selector:
    app: fe
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: {{ .Values.fe.service.port }}
      # nodePort: {{ .Values.fe.service.nodePort }}