apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: {{ .Values.fe.service.type }}
  selector:
    app: fe
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: {{ .Values.fe.service.port }}
      nodePort: 30007