kind: DaemonSet

input:
  type: tail
  path: /var/log/containers/*.log
  pos_file: /fluentd/log/fluentd-containers.log.pos
  tag: kubernetes.*
  format: json
  read_from_head: true
  time_key: time
  time_format: '%Y-%m-%dT%H:%M:%S.%NZ'

filter:
  type: kubernetes_metadata
  use_journal: false

output:
  type: elasticsearch
  host: elasticsearch-master.logging.svc.cluster.local
  port: 9200
  logstash_format: true
  logstash_prefix: fluentd
  include_tag_key: true
  flush_interval: 5s
