apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ktpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ktpm
            - name: POSTGRES_PASSWORD
              value: ktpm
            - name: POSTGRES_DB
              value: ktpm
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc