apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: ktpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
