fe:
  image: ndbaolam/bluemoon-fe:latest
  replicaCount: 1
  service:
    type: NodePort
    port: 80
  env:
    VITE_API_URL: http://be-service:8000


be:
  image: ndbaolam/bluemoon-be:latest
  replicaCount: 1
  service:
    type: NodePort
    port: 8000
  env:    
    DATABASE_URL: "postgresql://ktpm:ktpm@db-service:5432/ktpm"
    SECRET_KEY: secret-key
    ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: "60"

db:
  image: postgres:16-alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    storageClass: standard
    size: 3Gi
  env:
    POSTGRES_USER: ktpm
    POSTGRES_PASSWORD: ktpm
    POSTGRES_DB: ktpm
